# Permalinks
permalink: /posts/:title.html


# Config
markdown: kramdown
highlighter: rouge

# Setup
title: null tales
tagline: Geeky notes
url: https://www.nulltales.com
baseurl: ""


# About/contact
author:
  name: JT
  url: https://www.nulltales.com/about
  email: jt@nulltales.com
